name: Build and deploy website
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  push: {}

jobs:
  extract-params:
    name: Determine release parameters
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      publish-env: ${{ steps.setenv.outputs.envname }}
    steps:
      - id: setenv
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
              echo "envname=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
          else
              echo envname=staging >> "$GITHUB_OUTPUT"
          fi
  build-content:
    uses: MatthiasValvekens/gha-hakyll-build/.github/workflows/build-website.yml@v1
    permissions:
      contents: read
      packages: read
      id-token: write
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    needs: [build-content,extract-params]
    environment: ${{ needs.extract-params.outputs.publish-env }}
    steps:
    - name: Download generated content
      uses: actions/download-artifact@v3
      with:
        name: website-content
        path: _site/
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        SOURCE_DIR: _site/
        DEST_DIR: ${{ vars.S3_DEST_DIR }}
