name: Build and deploy website
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  push: {}

jobs:
  extract-params:
    name: Determine release parameters
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      publish-env: ${{ steps.setenv.outputs.envname }}
    steps:
      - id: setenv
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
              echo "envname=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
          else
              echo envname=staging >> "$GITHUB_OUTPUT"
          fi
  build-content:
    uses: MatthiasValvekens/gha-hakyll-build/.github/workflows/build-website.yml@v1
    permissions:
      contents: read
      packages: read
      id-token: write
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
    needs: [build-content,extract-params]
    environment: ${{ needs.extract-params.outputs.publish-env }}
    permissions:
      id-token: write
    steps:
    - name: Configure AWS Credentials with GHA OIDC for {{ github.ref }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        audience: ${{ vars.AWS_DEPLOY_AUDIENCE }}
        role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Download generated content
      uses: actions/download-artifact@v3
      with:
        name: website-content
        path: _site/
    - name: Upload to S3
      run: |
        aws s3 sync _site/ s3://${{ secrets.AWS_S3_BUCKET }}/${{ vars.S3_DEST_DIR }}
