name: Publish site builder image
on:
  workflow_dispatch: {}

jobs:
  publish-builder:
    uses: MatthiasValvekens/gha-hakyll-build/.github/workflows/release-build-image.yml@v3
    with:
      haskell-base-image-version: "9.10.3-slim-bookworm"
