name: Publish site builder image
on:
  push:
    branches: ["ci/*"]
  workflow_dispatch: {}
jobs:
  publish-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: docker-meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            ghcr.io/matthiasvalvekens/mvalvekens.be-hakyll
          tags: |
            type=raw,value=latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
